theme: jekyll-theme-midnight
title: Welcome to Visionary Cross edition created with EVT!
description: The Visionary Cross project is a multidisciplinary project. The aim is the development of new methodologies for the archiving and publication of texts and multimedia objects associated with the Visionary Cross of Anglo-Saxon England.
